### ISSUE TITLE
tests failing due to some missing PDFs

### ISSUE THREAD

**Issue by gedw99** [benoitkugler/pdf#1]
i wanted to have a play with the formfilling.

I have 2 files missing that stop tests in the form filling.

open test/open_action.pdf: no such file or directory

can't open file: open test/ModeleRecuFiscalEditable.pdf: no such file or directory

Is is because the files are too big for git practically ?

**Comment by benoitkugler** [comment]
Hi ! My apologies for the very late answer, for some reason I didn't see the notification..

I've added the files, so that tests should run properly.
