### ISSUE TITLE
Error missing Form XObject during ParsePDFFile

### ISSUE THREAD

**Issue by Chroq** [benoitkugler/pdf#7]
Hi Benoit,

I'm actually trying to fill a CERFA PDF file (https://www.assurance-maladie.ameli.fr/sites/default/files/formulaires/S3116i.pdf) but I'm struggling with this error : `missing Form XObject`

I've tried to "repair" my file but I load the file only when form is removed. I also check, it works with another PDF file with form.

Do you have any idea about I can solve this issue, please ?

**Comment by benoitkugler** [comment]
I'll give a look as soon as possible. 
Do you encounter the issue when reading the original PDF ? Or when trying to filling it ?

**Comment by Chroq** [comment]
Thank you, it's when I'm reading the PDF with `reader.ParsePDFFile`, I'm getting an `*errors.errorString`

**Comment by benoitkugler** [comment]
v0.0.9 should fix the issue, let me know if there is still something wrong.

**Comment by Chroq** [comment]
Thank you very much, Benoit ! It works like a charm :)
